### ISSUE TITLE
Incorrect value in sign determinant?

### ISSUE THREAD

**Issue by davidm494** [Bevy-Rust-GPU/bevy-pbr-rust#5]
This looks like a typo or copy/paste error, the "2.0" should probably be a "0.0". Or just remove the "* 2.0 - 1.0" and just return 1.0 and -1.0

https://github.com/Bevy-Rust-GPU/bevy-pbr-rust/blob/a0aba6242291877a5ed2a22e1f241f63947647d3/src/mesh/mod.rs#L55

**Comment by ProfLander** [comment]
Good catch, thanks - fixed in [9e7a0b0](https://github.com/Bevy-Rust-GPU/bevy-pbr-rust/commit/9e7a0b08ca90aa049180618ba3bde4aaba991144), and I've pushed the `v0.1.1` tag accordingly.
